Update hd_ticket.py
frappe/helpdesk pull request #1556
Opened 2023-09-12 16:28 UTC by ovresko

frappe.get_value does not guarantee returned  fields order from database, we have situations where values are reversed between enable_restrictions and ignore_restrictions (one's take the other field value)

`value = get_list(  <============== IN FRAPPE THIS DOES NOT GUARANTEE FIELDS ORDER
			doctype,
			filters=filters,
			fields=fields,
			debug=debug,
			limit_page_length=1,
			parent=parent,
			as_dict=as_dict,
		) 

	if as_dict:
		return value[0] if value else {}

	if not value:
		return

	return value[0] if len(fields) > 1 else value[0][0]
`

fixing by reading the result

2023-12-04 08:02 UTC, kingraphaii requested changes

2023-12-04 08:02 UTC, kingraphaii commented on helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
> +		restricttions = frappe.get_value(
spelling :)

2023-12-12 09:55 UTC, ankush commented
> frappe.get_value does not guarantee returned fields order from database, we have situations where values are reversed between enable_restrictions and ignore_restrictions (one's take the other field value)

This isn't possible. Can you share a reproducible example?

2023-12-12 10:54 UTC, ovresko commented
get_value internally uses get_list
reference: https://github.com/frappe/frappe/blob/7edb80bf5cb96700aaa14a2f6a7abe09afde4bbc/frappe/client.py#L129

get_list does not guarantee fields order since they are mapped to a dict based on doctype structure
any instance, set enable_restrictions to True, create 2 teams enter as one and create ticket for the other you'll see the ticket.
enable_restrictions taking ignore_restrictions's  value and ignore_restrictions  taking enable_restrictions's value

2023-12-12 15:41 UTC, ankush commented
@ovresko this bug should really be fixed in framework. I'll try it out. Thanks for explanation :+1:

2025-03-30 20:49 UTC, RitvikSardana commented
Not related to HD

2025-03-30 20:49 UTC, closed without merging